name: Terraform Plan
on:
  pull_request:
    branches: [ main ]
    
jobs:

  Terraform-Fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: 1.2.7
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 🎨 Apply terraform fmt